"""moves.ply smallint to match games.ply

Revision ID: e928ba0fc07f
Revises: c34bc93be1ca
Create Date: 2026-06-27 14:23:40.547568
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e928ba0fc07f'
down_revision: Union[str, None] = 'c34bc93be1ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('moves', 'ply',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('moves', 'ply',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
